export const Drugs = [
	"Paracetamol",
	"Ibuprofen",
	"Aspirin",
	"Diclofenac",
	"Naproxen",
	"Tramadol",
	"Codeine",
	"Morphine",
	"Fentanyl",
	"Ketoprofen",
	"Amoxicillin",
	"Ampicillin",
	"Ciprofloxacin",
	"Levofloxacin",
	"Ofloxacin",
	"Azithromycin",
	"Erythromycin",
	"Doxycycline",
	"Tetracycline",
	"Metronidazole",
	"Tinidazole",
	"Cefuroxime",
	"Ceftriaxone",
	"Cephalexin",
	"Ceftazidime",
	"Gentamicin",
	"Amikacin",
	"Vancomycin",
	"Linezolid",
	"Metformin",
	"Insulin",
	"Glimepiride",
	"Glibenclamide",
	"Sitagliptin",
	"Pioglitazone",
	"Acarbose",
	"Amlodipine",
	"Lisinopril",
	"Losartan",
	"Valsartan",
	"Hydrochlorothiazide",
	"Furosemide",
	"Spironolactone",
	"Atenolol",
	"Metoprolol",
	"Atorvastatin",
	"Rosuvastatin",
	"Simvastatin",
	"Pravastatin",
	"Omeprazole",
	"Pantoprazole",
	"Esomeprazole",
	"Lansoprazole",
	"Salbutamol",
	"Budesonide",
	"Fluticasone",
	"Montelukast",
	"Cetirizine",
	"Loratadine",
	"Fexofenadine",
	"Diphenhydramine",
	"Prednisolone",
	"Dexamethasone",
	"Hydrocortisone",
	"Betamethasone",
	"Chloroquine",
	"Artemether",
	"Lumefantrine",
	"Artesunate",
	"Albendazole",
	"Mebendazole",
	"Ivermectin",
	"Acetazolamide",
	"Allopurinol",
	"Amitriptyline",
	"Aripiprazole",
	"Baclofen",
	"Bisoprolol",
	"Bromhexine",
	"Buspirone",
	"Calcium Carbonate",
	"Candesartan",
	"Carbamazepine",
	"Carvedilol",
	"Chlorpheniramine",
	"Clindamycin",
	"Clopidogrel",
	"Colchicine",
	"Cyclizine",
	"Cyproheptadine",
	"Desloratadine",
	"Diazepam",
	"Digoxin",
	"Domperidone",
	"Donepezil",
	"Duloxetine",
	"Enalapril",
	"Escitalopram",
	"Ethambutol",
	"Ethinylestradiol",
	"Famotidine",
	"Ferrous Sulfate",
	"Fluconazole",
	"Fluoxetine",
	"Fluphenazine",
	"Folic Acid",
	"Gabapentin",
	"Gliclazide",
	"Haloperidol",
	"Heparin",
	"Imipramine",
	"Indomethacin",
	"Isosorbide Dinitrate",
	"Ketoconazole",
	"Labetalol",
	"Lamivudine",
	"Lamotrigine",
	"Levothyroxine",
	"Lithium Carbonate",
	"Magnesium Sulfate",
	"Meclizine",
	"Mefenamic Acid",
	"Methadone",
	"Methotrexate",
	"Miconazole",
	"Midazolam",
	"Mirtazapine",
	"Misoprostol",
	"Mupirocin",
	"Naloxone",
	"Nevirapine",
	"Niclosamide",
	"Nifedipine",
	"Nitrofurantoin",
	"Nitroglycerin",
	"Nystatin",
	"Olanzapine",
	"Ondansetron",
	"Oxcarbazepine",
	"Oxybutynin",
	"Penicillin V",
	"Phenobarbital",
	"Phenytoin",
	"Prochlorperazine",
	"Promethazine",
	"Propranolol",
	"Pyridoxine",
	"Quetiapine",
	"Quinine",
	"Ranitidine",
	"Rifampicin",
	"Risperidone",
	"Sertraline",
	"Sildenafil",
	"Sodium Valproate",
	"Sucralfate",
	"Sulfasalazine",
	"Tamoxifen",
	"Tenofovir",
	"Terbinafine",
	"Thiamine",
	"Tizanidine",
	"Topiramate",
	"Tranexamic Acid",
	"Trazodone",
	"Triamterene",
	"Trimethoprim",
	"Ursodeoxycholic Acid",
	"Valacyclovir",
	"Venlafaxine",
	"Verapamil",
	"Vitamin C",
	"Vitamin D3",
	"Warfarin",
	"Zidovudine",
	"Zinc Sulfate",
	"Zolpidem",
	"Acetaminophen",
	"Adapalene",
	"Albuterol",
	"Alendronate",
	"Alogliptin",
	"Amantadine",
	"Amitraz",
	"Anastrozole",
	"Aprepitant",
	"Atazanavir",
	"Azathioprine",
	"Bacitracin",
	"Beclomethasone",
	"Benzonatate",
	"Benztropine",
	"Bicalutamide",
	"Bimatoprost",
	"Brimonidine",
	"Buprenorphine",
	"Bupropion",
	"Cabergoline",
	"Cefepime",
	"Cefixime",
	"Celecoxib",
	"Cefotaxime",
	"Chloramphenicol",
	"Cimetidine",
	"Ciprofloxacin/Dexamethasone",
	"Clarithromycin",
	"Clobetasol",
	"Clonazepam",
	"Clonidine",
	"Clozapine",
	"Colistin",
	"Conjugated Estrogens",
	"Cromolyn Sodium",
	"Cyclobenzaprine",
	"Cyclosporine",
	"Dabigatran",
	"Dapagliflozin",
	"Desmopressin",
	"Dexlansoprazole",
	"Dexmethylphenidate",
	"Dexmedetomidine",
	"Dextromethorphan",
	"Diazoxide",
	"Dicyclomine",
	"Digoxin Immune Fab",
	"Diltiazem",
	"Dipyridamole",
	"Doripenem",
	"Doxazosin",
	"Doxepin",
	"Dronedarone",
	"Dulaglutide",
	"Edoxaban",
	"Efavirenz",
	"Eletriptan",
	"Empagliflozin",
	"Enoxaparin",
	"Entacapone",
	"Eplerenone",
	"Epoetin Alfa",
	"Eszopiclone",
	"Etanercept",
	"Ethinyl Estradiol/Norgestimate",
	"Etoricoxib",
	"Exenatide",
	"Famciclovir",
	"Febuxostat",
	"Fenofibrate",
	"Fentanyl Patch",
	"Fexofenadine/Pseudoephedrine",
	"Finasteride",
	"Fluocinonide",
	"Fluorouracil",
	"Fluticasone/Salmeterol",
	"Fosinopril",
	"Ganciclovir",
	"Gemfibrozil",
	"Glipizide",
	"Glyburide",
	"Granisetron",
	"Haloperidol Decanoate",
	"Heparin Sodium",
	"Hydralazine",
	"Hydroxychloroquine",
	"Hydroxyzine",
	"Hyoscyamine",
	"Ibutilide",
	"Imatinib",
	"Indapamide",
	"Infliximab",
	"Insulin Aspart",
	"Insulin Detemir",
	"Insulin Glargine",
	"Insulin Lispro",
	"Ipratropium",
	"Isotretinoin",
	"Ketorolac",
	"Lacosamide",
	"Latamoxef",
	"Levetiracetam",
	"Levonorgestrel",
	"Levothyroxine Sodium",
	"Lidocaine",
	"Linagliptin",
	"Liraglutide",
	"Lithium",
	"Loratadine/Pseudoephedrine",
	"Lorazepam",
	"Losartan/HCTZ",
	"Lovastatin",
	"Lurasidone",
	"Magnesium Hydroxide",
	"Meloxicam",
	"Memantine",
	"Meropenem",
	"Metaxalone",
	"Methimazole",
	"Methocarbamol",
	"Methylphenidate",
	"Methylprednisolone",
	"Metoclopramide",
	"Metolazone",
	"Metoprolol Succinate",
	"Metoprolol Tartrate",
	"Milrinone",
	"Minocycline",
	"Montelukast Sodium",
	"Morphine Sulfate",
	"Moxifloxacin",
	"Mycophenolate Mofetil",
	"Nabumetone",
	"Naltrexone",
	"Natalizumab",
	"Nebivolol",
	"Nefazodone",
	"Neostigmine",
	"Nifedipine ER",
	"Nitazoxanide",
	"Nitrofurantoin Macrocrystals",
	"Nitroglycerin Patch",
	"Norethindrone",
	"Nortriptyline",
	"Olmesartan",
	"Olopatadine",
	"Omeprazole/Sodium Bicarbonate",
	"Ondansetron ODT",
	"Oseltamivir",
	"Oxycodone",
	"Oxybutynin ER",
	"Paclitaxel",
	"Palonosetron",
	"Pantoprazole Sodium",
	"Paricalcitol",
	"Pemetrexed",
	"Pentoxifylline",
	"Perindopril",
	"Phenazopyridine",
	"Phentermine",
	"Phenytoin Sodium",
	"Pioglitazone Hydrochloride",
	"Piperacillin/Tazobactam",
	"Prasugrel",
	"Pravastatin Sodium",
	"Prednisone",
	"Pregabalin",
	"Primidone",
	"Promethazine HCl",
	"Propafenone",
	"Propranolol ER",
	"Quetiapine Fumarate",
	"Quinapril",
	"Ranolazine",
	"Rifaximin",
	"Risperidone Oral Solution",
	"Rivaroxaban",
	"Ropinirole",
	"Rosuvastatin Calcium",
	"Salmeterol",
	"Saxagliptin",
	"Selegiline",
	"Sertraline HCl",
	"Sildenafil Citrate",
	"Sitagliptin Phosphate",
	"Sodium Bicarbonate",
	"Sotalol",
	"Sulfasalazine Enteric Coated",
	"Sunitinib",
	"Sumatriptan",
	"Tacrolimus",
	"Tamoxifen Citrate",
	"Tamsulosin",
	"Tegaserod",
	"Telmisartan",
	"Temazepam",
	"Teneligliptin",
	"Tenofovir Disoproxil Fumarate",
	"Terazosin",
	"Terbinafine Hydrochloride",
	"Tetrabenazine",
	"Thalidomide",
	"Thiamine Hydrochloride",
	"Thyroxine",
	"Tiotropium",
	"Tizanidine HCl",
	"Tobramycin",
	"Tolterodine",
	"Tramadol HCl",
	"Trazodone HCl",
	"Triamcinolone",
	"Triamterene/HCTZ",
	"Trientine",
	"Trifluridine",
	"Trimethoprim/Sulfamethoxazole",
	"Umeclidinium",
	"Ursodiol",
	"Valacyclovir HCl",
	"Valproic Acid",
	"Vardenafil",
	"Venetoclax",
	"Venlafaxine HCl",
	"Verapamil SR",
	"Vildagliptin",
	"Vitamin B12",
	"Vitamin E",
	"Voriconazole",
	"Warfarin Sodium",
	"Zaleplon",
	"Zidovudine/Lamivudine",
	"Zinc Acetate",
	"Ziprasidone",
	"Zolmitriptan",
	"Zonisamide",
];
