export interface Patient {
	id: string;
	first_name: string;
	last_name: string;
	age: string;
}

export const patients: Patient[] = [
	{ id: "PAT-001", first_name: "John", last_name: "Doe", age: "45" },
	{ id: "PAT-002", first_name: "Mary", last_name: "Johnson", age: "32" },
	{ id: "PAT-003", first_name: "Ahmed", last_name: "Sule", age: "58" },
	{ id: "PAT-004", first_name: "Sarah", last_name: "Williams", age: "27" },
	{ id: "PAT-005", first_name: "Michael", last_name: "Brown", age: "41" },
	{ id: "PAT-006", first_name: "Aisha", last_name: "Abdul", age: "36" },
	{ id: "PAT-007", first_name: "Daniel", last_name: "Okafor", age: "50" },
	{ id: "PAT-008", first_name: "Grace", last_name: "Adeyemi", age: "29" },
	{ id: "PAT-009", first_name: "James", last_name: "Miller", age: "63" },
	{ id: "PAT-010", first_name: "Fatima", last_name: "Bello", age: "34" },

	{ id: "PAT-011", first_name: "Robert", last_name: "Taylor", age: "47" },
	{ id: "PAT-012", first_name: "Blessing", last_name: "Eze", age: "22" },
	{ id: "PAT-013", first_name: "Samuel", last_name: "Clark", age: "55" },
	{ id: "PAT-014", first_name: "Hauwa", last_name: "Mohammed", age: "39" },
	{ id: "PAT-015", first_name: "David", last_name: "Anderson", age: "61" },
	{ id: "PAT-016", first_name: "Ruth", last_name: "Onyekachi", age: "31" },
	{ id: "PAT-017", first_name: "Peter", last_name: "Okoye", age: "44" },
	{ id: "PAT-018", first_name: "Esther", last_name: "Akinwale", age: "26" },
	{ id: "PAT-019", first_name: "Thomas", last_name: "Harris", age: "68" },
	{ id: "PAT-020", first_name: "Zainab", last_name: "Sadiq", age: "35" },

	{ id: "PAT-021", first_name: "Ibrahim", last_name: "Lawal", age: "52" },
	{ id: "PAT-022", first_name: "Victoria", last_name: "Stone", age: "28" },
	{ id: "PAT-023", first_name: "Anthony", last_name: "Edwards", age: "59" },
	{ id: "PAT-024", first_name: "Mariam", last_name: "Yusuf", age: "33" },
	{
		id: "PAT-025",
		first_name: "Christopher",
		last_name: "Walker",
		age: "46",
	},
	{ id: "PAT-026", first_name: "Deborah", last_name: "Ajayi", age: "37" },
	{ id: "PAT-027", first_name: "Joseph", last_name: "Martins", age: "64" },
	{ id: "PAT-028", first_name: "Khadija", last_name: "Umar", age: "24" },
	{ id: "PAT-029", first_name: "Nathan", last_name: "King", age: "42" },
	{ id: "PAT-030", first_name: "Halima", last_name: "Ismail", age: "48" },

	{ id: "PAT-031", first_name: "Paul", last_name: "Baker", age: "56" },
	{ id: "PAT-032", first_name: "Janet", last_name: "Olatunji", age: "34" },
	{ id: "PAT-033", first_name: "Kelvin", last_name: "Moore", age: "29" },
	{ id: "PAT-034", first_name: "Safiya", last_name: "Aliyu", age: "41" },
	{ id: "PAT-035", first_name: "Brian", last_name: "Scott", age: "62" },
	{ id: "PAT-036", first_name: "Comfort", last_name: "Ibrahim", age: "38" },
	{ id: "PAT-037", first_name: "Henry", last_name: "Lewis", age: "51" },
	{ id: "PAT-038", first_name: "Hadiza", last_name: "Tanko", age: "27" },
	{ id: "PAT-039", first_name: "Victor", last_name: "Nelson", age: "45" },
	{ id: "PAT-040", first_name: "Ngozi", last_name: "Okorie", age: "60" },

	{ id: "PAT-041", first_name: "Aaron", last_name: "White", age: "35" },
	{ id: "PAT-042", first_name: "Sadiya", last_name: "Musa", age: "23" },
	{ id: "PAT-043", first_name: "Justin", last_name: "Hall", age: "49" },
	{ id: "PAT-044", first_name: "Latifat", last_name: "Suleiman", age: "31" },
	{ id: "PAT-045", first_name: "Dennis", last_name: "Young", age: "67" },
	{ id: "PAT-046", first_name: "Amaka", last_name: "Nwoye", age: "28" },
	{ id: "PAT-047", first_name: "Raymond", last_name: "Green", age: "54" },
	{ id: "PAT-048", first_name: "Maryam", last_name: "Danladi", age: "36" },
	{ id: "PAT-049", first_name: "Stephen", last_name: "Adams", age: "43" },
	{ id: "PAT-050", first_name: "Hadassah", last_name: "Joseph", age: "25" },

	{ id: "PAT-051", first_name: "Oscar", last_name: "Reed", age: "58" },
	{ id: "PAT-052", first_name: "Aminu", last_name: "Garba", age: "40" },
	{ id: "PAT-053", first_name: "Philip", last_name: "Carter", age: "61" },
	{ id: "PAT-054", first_name: "Samantha", last_name: "Brooks", age: "34" },
	{ id: "PAT-055", first_name: "Tunde", last_name: "Balogun", age: "47" },
	{ id: "PAT-056", first_name: "Lydia", last_name: "Morgan", age: "29" },
	{ id: "PAT-057", first_name: "Isaac", last_name: "Turner", age: "52" },
	{ id: "PAT-058", first_name: "Rahmat", last_name: "Salami", age: "38" },
	{ id: "PAT-059", first_name: "Caleb", last_name: "Parker", age: "44" },
	{ id: "PAT-060", first_name: "Aminah", last_name: "Abbas", age: "33" },

	{ id: "PAT-061", first_name: "Martin", last_name: "Cole", age: "65" },
	{ id: "PAT-062", first_name: "Yetunde", last_name: "Ogun", age: "27" },
	{ id: "PAT-063", first_name: "George", last_name: "Bell", age: "56" },
	{ id: "PAT-064", first_name: "Sola", last_name: "Adebayo", age: "41" },
	{ id: "PAT-065", first_name: "Leonard", last_name: "Ward", age: "60" },
	{ id: "PAT-066", first_name: "Habiba", last_name: "Shehu", age: "35" },
	{ id: "PAT-067", first_name: "Eric", last_name: "Foster", age: "48" },
	{ id: "PAT-068", first_name: "Moses", last_name: "Yakubu", age: "54" },
	{ id: "PAT-069", first_name: "Patrick", last_name: "Gray", age: "39" },
	{ id: "PAT-070", first_name: "Amina", last_name: "Kabir", age: "31" },

	{ id: "PAT-071", first_name: "Trevor", last_name: "Watson", age: "46" },
	{ id: "PAT-072", first_name: "Salim", last_name: "Kano", age: "59" },
	{ id: "PAT-073", first_name: "Bruce", last_name: "Long", age: "63" },
	{ id: "PAT-074", first_name: "Rashida", last_name: "Muktar", age: "28" },
	{ id: "PAT-075", first_name: "Allen", last_name: "Price", age: "51" },
	{ id: "PAT-076", first_name: "Joy", last_name: "Chukwu", age: "34" },
	{ id: "PAT-077", first_name: "Harold", last_name: "Evans", age: "67" },
	{ id: "PAT-078", first_name: "Zarah", last_name: "Mustapha", age: "26" },
	{ id: "PAT-079", first_name: "Leon", last_name: "Phillips", age: "42" },
	{ id: "PAT-080", first_name: "Kemi", last_name: "Ojo", age: "30" },

	{ id: "PAT-081", first_name: "Dominic", last_name: "Roberts", age: "55" },
	{ id: "PAT-082", first_name: "Sadiq", last_name: "Abubakar", age: "48" },
	{ id: "PAT-083", first_name: "Julian", last_name: "Turnbull", age: "61" },
	{ id: "PAT-084", first_name: "Zainab", last_name: "Gidado", age: "36" },
	{ id: "PAT-085", first_name: "Frank", last_name: "Hughes", age: "69" },
	{ id: "PAT-086", first_name: "Binta", last_name: "Saleh", age: "33" },
	{ id: "PAT-087", first_name: "Russell", last_name: "Wood", age: "50" },
	{ id: "PAT-088", first_name: "Peace", last_name: "Ifeanyi", age: "24" },
	{ id: "PAT-089", first_name: "Gavin", last_name: "Owen", age: "45" },
	{ id: "PAT-090", first_name: "Latifa", last_name: "Hassan", age: "37" },

	{ id: "PAT-091", first_name: "Neil", last_name: "Ramsey", age: "58" },
	{ id: "PAT-092", first_name: "Kabiru", last_name: "Sani", age: "41" },
	{ id: "PAT-093", first_name: "Howard", last_name: "Morris", age: "66" },
	{ id: "PAT-094", first_name: "Sakina", last_name: "Bako", age: "29" },
	{ id: "PAT-095", first_name: "Colin", last_name: "Ferguson", age: "53" },
	{ id: "PAT-096", first_name: "Halimat", last_name: "Raji", age: "35" },
	{ id: "PAT-097", first_name: "Trevor", last_name: "Knight", age: "47" },
	{ id: "PAT-098", first_name: "Nafisa", last_name: "Yahaya", age: "32" },
	{ id: "PAT-099", first_name: "Wayne", last_name: "Porter", age: "64" },
	{ id: "PAT-100", first_name: "Rabiatu", last_name: "Adam", age: "27" },

	{ id: "PAT-101", first_name: "Clifford", last_name: "Barnes", age: "59" },
	{ id: "PAT-102", first_name: "Sadiya", last_name: "Usman", age: "34" },
	{ id: "PAT-103", first_name: "Elliot", last_name: "Hunt", age: "46" },
	{ id: "PAT-104", first_name: "Maimuna", last_name: "Abdullahi", age: "28" },
	{ id: "PAT-105", first_name: "Stanley", last_name: "Fisher", age: "62" },
	{ id: "PAT-106", first_name: "Khadijah", last_name: "Balarabe", age: "31" },
	{ id: "PAT-107", first_name: "Wesley", last_name: "Griffin", age: "55" },
	{ id: "PAT-108", first_name: "Ramatu", last_name: "Sule", age: "39" },
	{ id: "PAT-109", first_name: "Adrian", last_name: "Coleman", age: "44" },
	{ id: "PAT-110", first_name: "Safiya", last_name: "Mahmud", age: "26" },

	{ id: "PAT-111", first_name: "Bernard", last_name: "Knight", age: "67" },
	{ id: "PAT-112", first_name: "Hajara", last_name: "Yusuf", age: "33" },
	{ id: "PAT-113", first_name: "Roland", last_name: "Stewart", age: "52" },
	{ id: "PAT-114", first_name: "Zulaiha", last_name: "Musa", age: "29" },
	{ id: "PAT-115", first_name: "Edwin", last_name: "Palmer", age: "60" },
	{ id: "PAT-116", first_name: "Asma'u", last_name: "Sadiq", age: "35" },
	{ id: "PAT-117", first_name: "Marcus", last_name: "Lowe", age: "48" },
	{ id: "PAT-118", first_name: "Nana", last_name: "Yakubu", age: "27" },
	{ id: "PAT-119", first_name: "Douglas", last_name: "Richards", age: "64" },
	{
		id: "PAT-120",
		first_name: "Rukayya",
		last_name: "Abdulrahman",
		age: "31",
	},
];
